services:
  doubao-free-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doubao-free-api
    restart: always
    ports:
      - "5566:8000"  # 将容器的8000端口映射到主机的5566端口
    volumes:
      - ./configs:/app/configs  # 挂载配置目录
      - ./logs:/app/logs  # 挂载日志目录（可选）
    environment:
      - NODE_ENV=dev  # 设置环境变量
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


# docker-compose up -d